[workspace]
resolver = "2"

members = [
  "server",
  "client",
  "formnet",
  "hostsfile",
  "shared",
  "publicip",
  "netlink-request",
]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"
